# Generated by Django 4.1 on 2023-11-13 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('tipo', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('largo', models.PositiveIntegerField(default=0)),
                ('alto', models.PositiveIntegerField(default=0)),
                ('profundidad', models.PositiveIntegerField(default=0)),
                ('color', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='libreria/static/img', verbose_name='Foto')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripcion')),
            ],
        ),
    ]
